[package]
name = "libveritas_zk"
version = "0.1.0"
edition = "2024"

[dependencies]
spacedb = { workspace = true }
borsh = { version = "1.6", default-features = false, features = ["derive"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
